coverage:
  precision: 2
  round: down
  range: 70...100
  status:
    project:
      default:
        target: auto
        threshold: 10%
        informational: true
    patch:
      default:
        informational: true

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: true

codecov:
  notify:
    wait_for_ci: false
    
ignore:
  - "*.pb.go"
  - "*.pb.gw.go"
  - "*.md"
  - "*.ts"
  - "actions/"
  - "assets/"
  - "docs/"
  - "integration/"
  - "scripts/"
