name: Release Binaries

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  binary:
    runs-on: ubuntu-latest
    env:
      working-directory: go/src/github.com/ignite/gex

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ env.working-directory }}
          fetch-depth: 0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          workdir: ${{ env.working-directory }}
          version: 1.13.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
