name: Lint

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - main
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint Go code
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/*.go
            **/*.plush
            go.mod
            go.sum

      - uses: actions/setup-go@v5
        if: env.GIT_DIFF
        with:
          go-version-file: go.mod
          cache: false

      - uses: golangci/golangci-lint-action@v4
        if: env.GIT_DIFF
        with:
          version: v1.54.2
          install-mode: goinstall
          args: --timeout 10m
          github-token: ${{ secrets.github_token }}
